is-executable claude || return

# Claude Code ships no completion generator (`claude completion` just starts a
# session) and Carapace has no `claude` spec, so the completer is vendored at
# ${ZDOTDIR}/completions/_claude rather than regenerated by command_completion.
#
# Source: github.com/wbingli/zsh-claudecode-completion (MIT) — regenerated
# daily upstream. To refresh, overwrite that file; it currently tracks the
# header-stamped Claude version. compinit already ran by the time application
# files load, so register the completer manually (same pattern as gh.zshrc).
(( ${fpath[(Ie)"${ZDOTDIR}/completions"]} )) || fpath=("${ZDOTDIR}/completions" $fpath)
autoload -Uz _claude
(( ${+_comps} )) || typeset -g -A _comps
_comps[claude]=_claude
