# type source target
#
# types can be "symlink" or "copy"
# source path is relative
# target path ~ is replaced with $HOME
#
symlink _bash_profile ~/.bash_profile
symlink _bashrc ~/.bashrc
symlink _bashrc.d ~/.bashrc.d
symlink _inputrc ~/.inputrc
symlink _vim ~/.vim
symlink _vimrc ~/.vimrc
symlink _aria2 ~/.aria2
symlink _zshrc ~/.zshrc
symlink _zshrc.d ~/.zshrc.d
symlink _zsh_profile ~/.zsh_profile
symlink _zshenv ~/.zshenv
symlink _gitconfig ~/.gitconfig
symlink _config/yamllint ~/.config/yamllint
copy _gitignore ~/.gitignore
