# type source target
#
# types can be "symlink" or "copy"
# source path is relative
# target path ~ is replaced with $HOME
#
# symlink _bash_profile ~/.bash_profile
# symlink _bashrc ~/.bashrc
# symlink _bashrc.d ~/.bashrc.d
# symlink _inputrc ~/.inputrc
symlink _vim ~/.vim
# symlink _zshrc ~/.config/zsh/.zshrc
# symlink _zshrc.d ~/.config/zsh/zshrc.d
# symlink _zsh_profile ~/.config/zsh/.zsh_profile
symlink _zshenv ~/.zshenv
symlink _config/zsh ~/.config/zsh
symlink _config/git ~/.config/git
symlink _config/aria2 ~/.config/aria2
symlink _config/yamllint ~/.config/yamllint
# copy _gitignore ~/.gitignore
