# type source target
#
# types can be "symlink" or "copy"
# source path is relative
# target path ~ is replaced with $HOME
#
#symlink vim ~/.vim
symlink config/zsh/.zshenv ~/.zshenv
symlink config/zsh ~/.config/zsh
symlink config/git ~/.config/git
symlink config/vim ~/.config/vim
symlink config/aria2 ~/.config/aria2
symlink config/yamllint ~/.config/yamllint
