set nocompatible              " be iMproved, required
filetype off                  " required

set runtimepath^=$XDG_CONFIG_HOME/vim
set runtimepath+=$XDG_DATA_HOME/vim
set runtimepath+=$XDG_CONFIG_HOME/vim/after

set packpath^=$XDG_DATA_HOME/vim,$XDG_CONFIG_HOME/vim
set packpath+=$XDG_CONFIG_HOME/vim/after,$XDG_DATA_HOME/vim/after

let g:netrw_home = $XDG_DATA_HOME."/vim"
call mkdir($XDG_DATA_HOME."/vim/spell", 'p')

set backupdir=$XDG_STATE_HOME/vim/backup | call mkdir(&backupdir, 'p')
set directory=$XDG_STATE_HOME/vim/swap   | call mkdir(&directory, 'p')
set undodir=$XDG_STATE_HOME/vim/undo     | call mkdir(&undodir,   'p')
set viewdir=$XDG_STATE_HOME/vim/view     | call mkdir(&viewdir,   'p')

if !has('nvim') | set viminfofile=$XDG_STATE_HOME/vim/viminfo | endif

" Plugins are installed as native packages under
" $XDG_DATA_HOME/vim/pack/plugins/start/* by setup.py (see manifest.json):
"   vim-fugitive, catppuccin, lightline, ale, fzf, fzf.vim,
"   vim-surround, vim-repeat, vim-gitgutter, vim-sleuth
filetype plugin indent on    " required

" To ignore plugin indent changes, instead use:
"filetype plugin on

set t_Co=256

" have syntax highlighting in terminals which can display colours:
if has('syntax') && (&t_Co > 2)
  syntax on
endif

" have command-line completion <Tab> (for filenames, help topics, option names)
" first list the available options and complete the longest common part, then
" have further <Tab>s cycle through the possibilities:
set wildmode=list:longest,full

" display the current mode and partially-typed commands in the status line:
set showmode
set showcmd

" added 2015-09-16
" Set to auto read when a file is changed from the outside
set autoread

"Always show current position
"set ruler

" Highlight search results
"set hlsearch

" search as characters are entered
set incsearch

" Highlight matching [{()}] when text indicator is over them
set showmatch
" How many tenths of a second to blink when matching brackets
set mat=2

" show line numbers
"set number
" was getting in the way of copy and paste!
" Use the location in the status line instead!

" show cursorline
set cursorline

" folding
set foldmethod=indent   "fold based on indent
set foldnestmax=10      "deepest fold is 10 levels
set nofoldenable        "dont fold by default
set foldlevel=1         "this is just what i use

" Indentation is auto-detected per file by vim-sleuth (and .editorconfig,
" which Vim 9 supports natively), so no per-filetype tabstop autocmds here.

" Returns true if paste mode is enabled
function! HasPaste()
    if &paste
        return 'PASTE MODE  '
    en
    return ''
endfunction

" Set color scheme
let g:catppuccin_flavour = 'mocha'
colorscheme catppuccin_mocha

" Statusline: lightline (catppuccin theme shipped by catppuccin/vim).
" lightline shows the mode, so we no longer need vim's own -- INSERT --.
set noshowmode
set laststatus=2
" Powerline/NerdFont separators (need a Nerd Font in the terminal; ghostty
" is configured with FiraCode Nerd Font Mono). This is lightline's equivalent
" of airline's old g:airline_powerline_fonts=1.
let g:lightline = {
\ 'colorscheme': 'catppuccin_mocha',
\ 'separator':    { 'left': "", 'right': "" },
\ 'subseparator': { 'left': "", 'right': "" },
\ 'active': {
\   'left':  [ [ 'mode', 'paste' ],
\              [ 'gitbranch', 'readonly', 'filename', 'modified' ] ],
\   'right': [ [ 'lineinfo' ], [ 'percent' ],
\              [ 'fileformat', 'fileencoding', 'filetype' ] ]
\ },
\ 'component_function': {
\   'gitbranch': 'LightlineGitbranch'
\ },
\ }

" Git branch with a NerdFont branch glyph (); empty outside a repo.
function! LightlineGitbranch() abort
    let l:branch = FugitiveHead()
    return l:branch !=# '' ? " " . l:branch : ''
endfunction

au BufNewFile,BufRead *.zshrc set filetype=zsh

" ----------------------------------------------------------------------------
" ALE: async linting + fixing. Linters auto-detect, but pin them per filetype
" to match the toolchain this repo already uses (yamllint, markdownlint,
" shellcheck/shfmt). Fixers run on save.
let g:ale_linters_explicit = 1
let g:ale_linters = {
\ 'sh':       ['shellcheck'],
\ 'zsh':      ['shellcheck'],
\ 'yaml':     ['yamllint'],
\ 'markdown': ['markdownlint'],
\ }
let g:ale_fixers = {
\ '*':        ['remove_trailing_lines', 'trim_whitespace'],
\ 'sh':       ['shfmt'],
\ 'zsh':      ['shfmt'],
\ }
let g:ale_fix_on_save = 1
" shellcheck: treat .zshrc etc. as bash-ish so it doesn't bail on zsh syntax.
let g:ale_sh_shellcheck_dialect = 'bash'
" Jump between problems.
nmap <silent> [d <Plug>(ale_previous_wrap)
nmap <silent> ]d <Plug>(ale_next_wrap)

" ----------------------------------------------------------------------------
" fzf.vim: fuzzy finding backed by the fzf/ripgrep/fd already on this system.
" :Files / :Buffers / :Rg are the workhorses; map the common ones.
let g:fzf_command_prefix = ''
nnoremap <silent> <leader>f :Files<CR>
nnoremap <silent> <leader>b :Buffers<CR>
nnoremap <silent> <leader>g :Rg<CR>

" Load all plugins now.
" Plugins need to be added to runtimepath before helptags can be generated.
packloadall
" Load all of the helptags now, after plugins have been loaded.
" All messages and errors will be ignored.
silent! helptags ALL
